### ISSUE TITLE
[BUG] When I went down one level in spleef, it said the opponent won.

### ISSUE THREAD

**Issue by n0TaN00b473** [JasonHorkles/Silverstone#20] opened 2020-08-03 22:19 UTC
#### Server this occurred in (in the player tab list):
Silverstone survival

#### World this occurred in (in the player tab list):
Normal world?

#### The coordinates at/near the glitch (if applicable):
n/a
#### My Minecraft username:
n0TaN00b473

#### What I was doing when the glitch occurred:
Spleef minigame

#### What happened:
When the opponent made me fall down a level at the TOP level, it said he won.

#### What was supposed to happen:
He was supposed to not win?

#### Any additional details that should be noted (pictures/videos of it happening, etc):
This was after Jason fixed the glitch of two people dying at the same time (nobody would win).

**Comment by JasonHorkles** [comment] 2020-08-03 22:51
It probably didn't reset correctly as I am unable to reproduce it now. Please comment on this issue if you encounter it again.

**Comment by n0TaN00b473** [comment] 2020-08-05 16:30
I happened again, i think it only happens with 3 players or something.

**Comment by n0TaN00b473** [comment] 2020-08-05 16:41
*it

**Comment by JasonHorkles** [comment] 2020-08-05 16:42
> *it

*you can edit messages btw*

**Comment by JasonHorkles** [comment] 2020-08-05 17:08
Did this happen the first time you had 3 people playing or after it reset later?

**Comment by n0TaN00b473** [comment] 2020-08-05 17:09
I don't know what you mean

**Comment by n0TaN00b473** [comment] 2020-08-05 17:10
I'm actually not entirely sure that there was 3 people the first time

**Comment by JasonHorkles** [comment] 2020-08-05 17:11
Did the problem happen when there were actually 3 people tho

**Comment by n0TaN00b473** [comment] 2020-08-05 17:11
yes?

**Comment by n0TaN00b473** [comment] 2020-08-05 17:12
except this time, there were 3 people at the top, and when somebody fell, it said someone at the top won

**Comment by n0TaN00b473** [comment] 2020-08-05 17:12
...if that makes sense

**Comment by JasonHorkles** [comment] 2020-08-05 17:13
3 people on the first layer of snow or on the very top of the game in the spectating area?

**Comment by n0TaN00b473** [comment] 2020-08-05 17:13
Oh, sorry. The first layer of snow.

**Comment by n0TaN00b473** [comment] 2020-08-05 17:13
Not spectating.

**Comment by n0TaN00b473** [comment] 2020-08-05 17:14
i can try to record it next time, if that helps

**Comment by JasonHorkles** [comment] 2020-08-05 17:14
OK so just to be clear: There were 3 people on the first layer of snow, 1 fell down a single layer, leaving 2 remaining at the first layer. Correct?
Yes that'd be very helpful.

**Comment by n0TaN00b473** [comment] 2020-08-05 17:15
Yes, and then it said one of the 2 people remaining on the first layer one.

**Comment by n0TaN00b473** [comment] 2020-08-06 03:12
This is not fixed, it happened again with me and GalaxyCat again. I knocked galaxy down one layer at the top layer and it said I won. I tried to record it but I couldn't, sorry.

**Comment by JasonHorkles** [comment] 2020-08-06 04:04
A possible fix has been implemented.

**Closed** 2020-08-17 03:57 UTC
Labels: Bug-Unconfirmed, Low Priority
